apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-pvc
  labels:
    type: local-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 5Mi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      type: local-pv
