
apiVersion: v1
kind: Pod
metadata:
  name: mysqlclient
  labels:
    name: mysql-pod
spec:
  containers:
  - name: cont-mysql
    image: mysql
    command: ["/bin/sh"]
    args: ["-c","mysql -u `cat /mnt/db-creds/user)` -p `cat /mnt/db-creds/password)` -h `cat /mnt/db-creds/host)`"]
    volumeMounts:
      - name: creds
        mountPath: "/mnt/dbcreds"
        readOnly: true
  volumes:
    - name: creds
      secret:
        secretName: dbcreds
    
